"""
Downloads DSM (first + last return) and DTM tiles from DEFRA's LIDAR
Composite API for every tile listed in required_dsm_tiles.txt (generated by
checks/list_required_dsm_tiles.py).

Deliberately standalone and dependency-free (stdlib only) so it can run
anywhere Python 3 is installed. Output always goes into data/dsm/, data/dtm/,
data/dsm_last_return/ *next to this script* (not your current working
directory) — so it doesn't matter where you run it from, or if you double-
click it. Copy this file plus data/required_dsm_tiles.txt together, then run
it, then drag the resulting data/ subfolders into the Codespace.

WARNING: this downloads a lot of data — measured average is ~60MB per
tile/product; across ~355 tiles x 2 products (DSM first-return + DTM —
last-return DSM is deferred, see PRODUCTS below) that's roughly 35-40GB.
Check disk space before running the full tile list.

Requests are deliberately throttled to one launch every REQUEST_INTERVAL_S
seconds globally (across all CONCURRENCY workers), after a prior run hit
HTTP 403s partway through — the API sits behind Azure API Management on a
shared subscription key, and 403 there means rate-limited, not "no data".
At 5s/request this is slow by design (roughly (remaining downloads) x 5s,
so upwards of an hour for a few hundred tiles) — CONCURRENCY only lets
already-launched transfers overlap while finishing, it doesn't speed up
how often new ones are allowed to start.

Usage:
    python3 download_dsm_dtm.py [path/to/required_dsm_tiles.txt]
"""

import io
import os
import sys
import threading
import time
import urllib.error
import urllib.request
import zipfile
from concurrent.futures import ThreadPoolExecutor, as_completed

BASE_URL = (
    "https://environment.data.gov.uk/tiles/collections/survey/"
    "{product}/{year}/{resolution}/{tile}?subscription-key=dspui"
)

# product slug -> local output directory.
# lidar_composite_last_return_dsm is deferred (needed later for flora/
# vegetation features, not buildings) — uncomment when we get to that.
PRODUCTS = {
    "lidar_composite_first_return_dsm": "data/dsm",
    "lidar_composite_dtm": "data/dtm",
    # "lidar_composite_last_return_dsm": "data/dsm_last_return",
}

RESOLUTION = 1
# Composite releases are yearly editions; a given tile may only be present in
# some of them. Try the most likely year first, then fall back.
YEARS = [2022, 2021, 2023, 2024, 2025, 2026, 2020]
REQUEST_TIMEOUT_S = 180  # a single ~50MB file can legitimately take 30-60s+
CONCURRENCY = 8  # how many downloads can be transferring at once — pacing of

# new requests firing is separately capped by REQUEST_INTERVAL_S below, so
# raising this only affects how many transfers overlap, not how fast new
# ones are launched.

# Minimum seconds between any two request *launches*, enforced globally
# across all worker threads (not per-thread) — a global lock, not a
# per-connection sleep, so 8-way concurrency still only fires one request
# every 5s. Deliberately conservative after hitting HTTP 403s (rate-limiting
# on the shared subscription key) partway through a prior run.
REQUEST_INTERVAL_S = 5.0
_rate_lock = threading.Lock()
_next_allowed_time = 0.0


def _throttle():
    """Blocks until at least REQUEST_INTERVAL_S has passed since the last
    request was allowed to fire, across all threads."""
    global _next_allowed_time
    with _rate_lock:
        now = time.monotonic()
        wait = _next_allowed_time - now
        if wait > 0:
            time.sleep(wait)
            now = time.monotonic()
        _next_allowed_time = now + REQUEST_INTERVAL_S


def quadrant_tile_to_sw_ref(tile):
    """'TQ53ne' -> 'TQ5535' (the SW-corner digit form the download API expects)."""
    letters, digits, quadrant = tile[:2], tile[2:4], tile[4:6]
    e10, n10 = int(digits[0]), int(digits[1])
    e_off = 5 if "e" in quadrant else 0
    n_off = 5 if "n" in quadrant else 0
    return f"{letters}{e10 * 10 + e_off:02d}{n10 * 10 + n_off:02d}"


def download_tile(product, tile, output_dir):
    """Returns 'skip', 'done', 'missing', 'blocked', or 'error'."""
    label = f"{product} {tile}"
    output_path = os.path.join(output_dir, f"{tile}.tif")
    if os.path.exists(output_path):
        print(f"  SKIP    {label}: already downloaded")
        return "skip"

    print(f"  START   {label}")
    sw_ref = quadrant_tile_to_sw_ref(tile)
    for year in YEARS:
        url = BASE_URL.format(product=product, year=year, resolution=RESOLUTION, tile=sw_ref)
        _throttle()
        try:
            with urllib.request.urlopen(url, timeout=REQUEST_TIMEOUT_S) as resp:
                data = resp.read()
        except urllib.error.HTTPError as e:
            if e.code == 403:
                # The API sits behind Azure API Management on a shared
                # subscription key — a 403 means the key/IP has been
                # rate-limited, not that this tile lacks data. Every other
                # year will 403 too, so retrying them is pointless; bail out
                # immediately rather than burning 6 more guaranteed-403
                # requests (and prolonging whatever triggered the block).
                print(f"  BLOCKED {label} {year}: HTTP 403 (rate-limited) — try again later")
                return "blocked"
            # Both 404 (year doesn't have this tile) and 500 (seen for tiles
            # with no survey coverage at all, e.g. sea/estuary) are treated
            # the same: try the next year rather than giving up immediately,
            # since we can't tell them apart from the status code alone.
            print(f"  {label} {year}: HTTP {e.code}, trying next year")
            continue
        except urllib.error.URLError as e:
            print(f"  {label} {year}: network error ({e.reason}), giving up on this tile")
            return "error"

        with zipfile.ZipFile(io.BytesIO(data)) as zf:
            tif_names = [n for n in zf.namelist() if n.endswith(".tif")]
            if not tif_names:
                print(f"  {label} {year}: zip had no .tif inside, trying next year")
                continue
            os.makedirs(output_dir, exist_ok=True)
            with zf.open(tif_names[0]) as src, open(output_path, "wb") as dst:
                dst.write(src.read())

        print(f"  DONE    {label}: got {year} edition ({len(data) / 1024 / 1024:.1f} MB)")
        return "done"

    print(f"  MISSING {label}: not available in any of {YEARS}")
    return "missing"


def main():
    # Resolve everything relative to this script's own location, not the
    # current working directory — so it writes to the same place whether you
    # run it via `python3 download_dsm_dtm.py` from this folder, from
    # somewhere else, or by double-clicking it.
    script_dir = os.path.dirname(os.path.abspath(__file__))

    tiles_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(script_dir, "data/required_dsm_tiles.txt")
    with open(tiles_path) as f:
        tiles = [line.strip() for line in f if line.strip()]

    jobs = [
        (product, tile, os.path.join(script_dir, relative_output_dir))
        for product, relative_output_dir in PRODUCTS.items()
        for tile in tiles
    ]
    print(f"{len(tiles)} tiles x {len(PRODUCTS)} products = {len(jobs)} downloads")
    print(f"Output will be written under: {script_dir}")
    print(f"Running {CONCURRENCY} at a time\n")

    missing = []
    blocked = []
    errors = []
    completed = 0
    with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
        futures = {pool.submit(download_tile, product, tile, output_dir): (product, tile) for product, tile, output_dir in jobs}
        for future in as_completed(futures):
            product, tile = futures[future]
            completed += 1
            result = future.result()
            if result == "missing":
                missing.append((product, tile))
            elif result == "blocked":
                blocked.append((product, tile))
            elif result == "error":
                errors.append((product, tile))
            print(f"  [{completed}/{len(jobs)}] {product} {tile}")

    print(f"\nDone. {len(missing) + len(blocked) + len(errors)} not downloaded:")
    if blocked:
        print(f"\n  BLOCKED ({len(blocked)}) — rate-limited, not actually missing. Just re-run the script")
        print("  later (already-downloaded tiles are skipped, so it'll only retry these):")
        for product, tile in blocked:
            print(f"    {product} {tile}")
    if missing:
        print(f"\n  MISSING ({len(missing)}) — genuinely absent from every year checked:")
        for product, tile in missing:
            print(f"    {product} {tile}")
    if errors:
        print(f"\n  NETWORK ERROR ({len(errors)}) — worth a retry too:")
        for product, tile in errors:
            print(f"    {product} {tile}")


if __name__ == "__main__":
    main()
